name: Scrape new data
on:
  push:
    branches:
      - master
jobs:
  scrape-data:
    name: Scraping data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scrapers
        uses: actions/checkout@v2
        with:
          repository: 'quacs/scraper'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Populate env
        run: printf "RIN=${{ secrets.RIN }}\nPASSWORD=${{ secrets.PASSWORD }}\nCURRENT_TERM=${{ secrets.CURRENT_TERM }}" > sis_scraper/.env

      - name: Scrape courses
        run: python3 sis_scraper/main.py

      - name: Scrape prerequisites
        run: |
          cp sis_scraper/courses.json prerequisites_scraper &&
          python3 prerequisites_scraper/main.py

      - name: Commit new data
        run: |
          git status;
          cp sis_scraper/courses.json ./ &&
          cp sis_scraper/parsed.rs ./ &&
          cp prerequisites_scraper/prerequisites.json ./ &&
          git add courses.json parsed.rs prerequisites.json &&
