name: Scrape new data
on:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  scrape-data:
    name: Scraping data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scrapers
        uses: actions/checkout@v2
        with:
          path: 'scraper'
          repository: 'quacs/scraper'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          ls

      - name: Populate env
        run: printf "RIN=${{ secrets.RIN }}\nPASSWORD=${{ secrets.PASSWORD }}\nCURRENT_TERM=${{ secrets.CURRENT_TERM }}" > scraper/sis_scraper/.env

      - name: Scrape courses
        run: python3 scraper/sis_scraper/main.py

      - name: Scrape prerequisites
        run: |
          cp courses.json scraper/prerequisites_scraper
          python3 scraper/prerequisites_scraper/main.py

      - name: Scrape faculty
        run: python3 scraper/faculty_directory_scraper/main.py

      - name: Scrape catalog
        run: python3 scraper/catalog_scraper/main.py

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          path: 'data'
          repository: 'quacs/quacs-data'
          clean: true

      - name: Commit new data
        run: |
          cp courses.json mod.rs data
          cp prerequisites.json data
          cp faculty.json data
          cp catalog.json data
          cd data
          git config user.name "QuACS" && git config user.email "eli@elischiff.org"
          git add courses.json mod.rs
          git add prerequisites.json
          git add faculty.json
          git add catalog.json
          git commit -m "$(date -u)"
          git push --force

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout quacs
        uses: actions/checkout@v2
        with:
          path: 'quacs'
          repository: 'quacs/quacs'
          submodules: 'recursive'

      - name: Update quacs submodules
        run: |
          cd quacs
          git submodule update --remote --recursive

      - name: Clean install quacs dependencies
        run: yarn install --frozen-lockfile

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run quacs deploy script
        run: |
          git config user.name "QuACS" && git config user.email "eli@elischiff.org"
          yarn gh-pages-deploy
